### ISSUE TITLE
脚本无法正确运行，如图

### ISSUE THREAD

**Issue by yiyu-liao** [Kevin-l-wu/MiscTools#1]
<img width="687" alt="image" src="https://user-images.githubusercontent.com/43663210/203963649-6ded1f38-6fb8-44dd-bc8a-0d997266f793.png">

**Comment by Kevin-l-wu** [comment]
感谢您的反馈，

diskutil list 命令对不同分区表格式，返回的分区类型的字符是不一样的，MBR分区返回是“Windows_NTFS“，GUID返回的是"Microsoft Basic Data"。

您的硬盘是GUID分区格式，之前的脚本是仅支持MBR分区（仅取”Windows_NTFS“字符），最新的提交已经支持GUID，您有时间的话可以测试一下。

如果还有其他问题，欢迎提出，我们一起探讨。

**Comment by Kevin-l-wu** [comment]
Ready to close
